version: '3.8'

services:
  hdhomerun-epg:
    build: .
    container_name: hdhomerun-epg
    restart: unless-stopped
    ports:
      - "8083:8083"  # Web server port
    environment:
      - HDHOMERUN_HOST=192.168.134.171  # Your HDHomeRun IP
      - OUTPUT_FILENAME=/output/epg.xml
      - DAYS=7
      - HOURS=3
      - DEBUG=on
      - TZ=America/New_York  # Set your timezone
      - CRON_SCHEDULE=0 3 * * *  # Daily at 3 AM
      - RUN_ON_START=true  # Run immediately on container start
      - WEB_PORT=8083
    volumes:
      - epg-data:/output  # Persistent storage for EPG file
      - epg-logs:/var/log  # Optional: persist logs

volumes:
  epg-data:
  epg-logs: